uint32 time_stamp       # us
float32 velocity_n      # m/s
float32 velocity_e      # m/s
float32 velocity_d      # m/s
float32 velocity_n_acc  # m/s
float32 velocity_e_acc  # m/s
float32 velocity_d_acc  # m/s
float64 latitude        # degree       
float64 longitude       # degree
float64 altitude        # m
float32 undulation
float32 latitude_acc  
float32 longitude_acc 
float32 altitude_acc
uint32 solution_status  




